services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${postgres_usr}
      POSTGRES_PASSWORD: ${postgres_psw}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${port}

  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run block"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db